### ISSUE TITLE
Skapa kontaktsida för Jimmy

### ISSUE THREAD

**Issue by SimonJCode** [SimonJCode/Hackaton#2]
Skapa en kontaktsida, döp den till "fornam_efternamn.html".
Sidan ska innehålla: 
namn, bild samt en lista på 4 saker gruppmedlemmen är bra på och avslutas med en länk till gruppmedlemmens Github-profil. Det skall även finnas en länk tillbaka till huvudsidan för gruppen.

**Comment by Tallbacka** [comment]
Fixar detta asap!

**Comment by Tallbacka** [comment]
Fixat!
